import '@/styles/Global.scss';
import Navbar from '@/components/Navbar';
import AuthProvider from '@/components/AuthProviders';
export const metadata = {
  title: "Prompt app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className="global-background-gradient">
            <Navbar />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
